# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-14 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20181113_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('-expiration_date',)},
        ),
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(related_name='items', to='menu.Item'),
        ),
    ]
