# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-11-14 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20181113_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='items',
            field=models.ManyToManyField(to='menu.Item'),
        ),
    ]
